# Generated by Django 5.0.6 on 2024-06-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='url',
            new_name='urls',
        ),
    ]
