# Generated by Django 5.0.6 on 2024-06-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0006_newspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newspage',
            new_name='Newspage1',
        ),
    ]
