# Generated by Django 5.0.6 on 2024-06-24 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0015_livescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livescore',
            old_name='urls',
            new_name='match',
        ),
        migrations.AddField(
            model_name='livescore',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
