# Generated by Django 5.0.6 on 2024-06-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0019_article1_lastp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastp',
            old_name='league',
            new_name='Article1',
        ),
    ]
