# Generated by Django 5.0.6 on 2024-06-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0021_article2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastp',
            name='Article2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lastps', to='sportapp.article2'),
            preserve_default=False,
        ),
    ]
