# Generated by Django 5.0.6 on 2024-06-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0028_news_article_1_paragraph1a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph1a',
            old_name='Home_article_9',
            new_name='News_article_1',
        ),
    ]
